language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: testing
      compiler: gcc
    - os: linux
      dist: testing
      compiler: clang
    - os: linux
      dist: unstable
      compiler: gcc
    - os: linux
      dist: unstable
      compiler: clang

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo apt-get update
       sudo apt-get install -y libsctp-dev libbz2-dev qtbase5-dev qtbase5-dev-tools qtchooser
    fi

script:
  - |
    ./bootstrap
    ./configure --enable-kernel-sctp --enable-static --disable-shared --enable-qt --enable-csp --disable-hsmgtverify --enable-test-programs
    make VERBOSE=1
