language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      group: travis_latest
    - os: linux
      dist: trusty
      compiler: clang
      group: travis_latest
    - os: osx
      compiler: clang
      group: travis_latest


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo apt-get update
       sudo apt-get install -y libsctp-dev libbz2-dev qtbase5-dev qtbase5-dev-tools qtchooser
    elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
       brew update
       brew install bzip2 qt
    fi

script:
  - |
    ./bootstrap
    ./configure --enable-kernel-sctp --enable-static --disable-shared --enable-qt --enable-csp --disable-hsmgtverify --enable-test-programs
    make VERBOSE=1
