language: c++

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: testing
    - os: linux
      dist: unstable

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo apt-get update
       sudo apt-get install -y libsctp-dev libbz2-dev qtbase5-dev qtbase5-dev-tools qtchooser
    fi

script:
  - |
    ./bootstrap
    ./configure --enable-kernel-sctp --enable-static --disable-shared --enable-qt --enable-csp --disable-hsmgtverify --enable-test-programs
    make VERBOSE=1
