language: c++

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: bionic
      env: T=normal

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo apt-get update
       sudo apt-get install -y libsctp-dev libbz2-dev qtbase5-dev qtbase5-dev-tools qtchooser
    fi

script:
  - |
    if [ "$T" = "normal" ] ; then
       ./bootstrap
       ./configure --enable-kernel-sctp --enable-static --disable-shared --enable-qt --enable-csp --disable-hsmgtverify --enable-test-programs
       make VERBOSE=1
    fi

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
    only:
        - master
        - cmake
